/* tslint:disable */// Generated by Haxe TypeScript Declaration Generator :)

export type AppSettings = {
	appUiScale: number;
	autoInstallUpdates: boolean;
	autoWorldModeSwitch: any;
	blurMask: boolean;
	colorBlind: boolean;
	editorUiScale: number;
	emptySpaceSelection: boolean;
	fieldsRender: any;
	grid: boolean;
	lastKnownVersion: string;
	lastProject: {filePath: string, levelUid: number};
	lastUiDirs: {path: string, project?: string, uiId: string}[];
	mouseWheelSpeed: number;
	navigationKeys: any;
	nearbyTilesRenderingDist: number;
	openLastProject: boolean;
	projectTrusts: {iid: string, trusted: boolean}[];
	recentDirColors: {col: string, path: string}[];
	recentDirs: string[];
	recentProjects: string[];
	showDetails: boolean;
	singleLayerMode: boolean;
	singleLayerModeIntensity: number;
	startFullScreen: boolean;
	tileEnumOverlays: boolean;
	tileStacking: boolean;
	uiStates: {id: string, val: number}[];
	useBestGPU: boolean;
	zenMode: boolean;
}

export class ElectronMain {
	constructor();
	main(in_settings: AppSettings): void;
	quit(): void;
	static APP_RESOURCE_DIR: string;
}