name: Publish Package to npmjs
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3
      - run: haxe -version

      # Install haxe libs
      - run: haxe setup.hxml

      # Compile with haxe
      - run: haxe main.debug.hxml
      - run: haxe renderer.debug.hxml
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@nanite-factory-games'
      - run: cd app && npm ci
      - run: cd app && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}